import url from './config.js';

const baseUrl = url.base;

export default {
  data: baseUrl + "system/data/dictionary/getkvlist",  //数据字典
  login: baseUrl + "auth/token",
  logout: baseUrl + "auth/logout",
  refreshToken: baseUrl + "auth/token/refresh",
  menu: baseUrl + "menu",
  manageList: baseUrl + "userlist",
  promiseList: baseUrl + "userrolelist",
  adduser: baseUrl + "adduser",
  userinfo: baseUrl + "userinfo",
  userdel: baseUrl + "userdel",
  userrole: baseUrl + "userrole",
  userroleinfo: baseUrl + "userroleinfo",
  delUserRole: baseUrl + "userroledel",
  jdzxdjlist: baseUrl + "getconsultation",   //咨询登记列表
  findconsultlist: baseUrl + "findconsultlist",   //咨询登记查询
  addzxdjlist: baseUrl + "addconsultation",  //添加/修改咨询登记表
  ckzxdjlist: baseUrl + "consultationdetail",  //查看咨询登记表详情
  delzxdjlist: baseUrl + "deleteconsultation",  //删除咨询登记
  jdyydjlist: baseUrl + "appointmentlist",   //预约登记列表
  appointmentsearch: baseUrl + "appointmentsearch",   //预约登记查询列表
  addappointments: baseUrl + "addappointments",   //预约登记添加列表
  appointmentdetail: baseUrl + "appointmentdetail",   //预约登记详情列表
  delyydjdjlist: baseUrl + "delappointment",  //删除预约登记
  jdrzdjlist: baseUrl + "eldercheckinlist",   //入住登记列表
  deleldercheckin: baseUrl + "deleldercheckin",   //入住登记删除
  eldercheckininfo: baseUrl + "eldercheckininfo",   //入住登记-老人基本信息详情
  elderrelativelist: baseUrl + "elderrelativelist",   //入住登记-老人亲属信息列表
  jdwwcdjjcxidjlist: baseUrl + "oldmanelderslist",    //未完成登记-基础信息登记
  addelders: baseUrl + "addelders",    //未完成登记-基础信息登记添加
  detailelders: baseUrl + "detailelders",    //未完成登记-基础信息登记详情
  jdwwcdjjkpgdjlist: baseUrl + "elderhealthevaluationslist",    //未完成登记-健康评估登记
  jdwwcdjcycwdjlist: baseUrl + "elderrecipebedlist",    //未完成登记-餐饮床位护理登记
  jdwwcdjrzjfdjlist: baseUrl + "getfeesettlementlist",    //未完成登记-入住缴费登记
  jdtzdjlist: baseUrl + "eldercheckoutdetaillist",   //退住详情列表
  //费用管理
  imprestrecordlist: baseUrl + "imprestrecordlist",   //预存管理列表及查询
  addimprestrecord: baseUrl + "addimprestrecord",   //预存管理添加列表
  detailImpredetail: baseUrl + "detailImpredetail",   //预存管理详情列表
  feementsearch: baseUrl + "feementsearch",   //入住缴费查询
  getfeementlist: baseUrl + "getfeementlist",   //入住缴费列表
  addeldersnursingscheme: baseUrl + "addeldersnursingscheme",   //费用调整列表/添加
  costtypelist: baseUrl + "costtypelist",   //费用类别列表
  costtype: baseUrl + "costtype",   //费用类别增加/修改
  costtypedetails: baseUrl + "costtypedetails",   //费用类别详情
  costtypedel: baseUrl + "costtypedel",   //费用类别删除
  pricetypelist: baseUrl + "pricetypelist",   //初始费用列表
  updatepricetype: baseUrl + "updatepricetype",   //设置初始费用
  getfeemanagelists: baseUrl + "getfeemanagelists",   //欠费管理列表/查询
  paymentrecordslist: baseUrl + "paymentrecordslist",  //费用流水

  findoutregistrations: baseUrl + "findoutregistrations",   //玩出登记列表及查询
  deleteoutregistrations: baseUrl + "deleteoutregistrations",  //删除外出登记
  addoutregistrations: baseUrl + "addoutregistrations", //添加修改外出登记
  outregistrationsdetail: baseUrl + "outregistrationsdetail", //玩出登记详情
  visitlist: baseUrl + "visitlist", //探访登记列表
  addvisits: baseUrl + "addvisits", //增加探访登记
  visitssearch: baseUrl + "visitssearch", //探访登记搜索
  overvisits: baseUrl + "overvisits", //探访结束
  delvisits: baseUrl + "delvisits", //探访删除
  visitsdetail: baseUrl + "visitsdetail", //探访登记详情
  eldercheckoutregisterlist: baseUrl + "eldercheckoutregisterlist", //退住登记列表
  eldercheckoutdetail: baseUrl + "eldercheckoutdetail",  //退住登记详情
  eldercheckoutstore: baseUrl + "eldercheckoutstore",  //退住登记办理
  eldercheckoutsearch: baseUrl + "eldercheckoutsearch", //退住登记搜索
  eldercheckoutdetaillist: baseUrl + "eldercheckoutdetaillist", //退住详情列表
  eldercheckoutdetailsearch: baseUrl + "eldercheckoutdetailsearch", //退住详情搜索
  accidentlist: baseUrl + "accidentlist",  //事故记录列表
  accident: baseUrl + "accident",  //添加修改事故记录
  accidentinfo: baseUrl + "accidentinfo",  //事故记录详情
  accidentdel: baseUrl + "accidentdel",  //删除事故记录
  accidenttypelist: baseUrl + "accidenttypelist", //事故类型列表
  bedtypeslist: baseUrl + "bedtypeslist",  //床位类型列表
  deletebedtypes: baseUrl + "deletebedtypes", //床位类型删除
  RecipesDetailBedType: baseUrl + "beddetail", //床位类型详情
  addBedtype: baseUrl + "addbed",  //添加修改床位类型
  buildinglist: baseUrl + "buildinglist",  //楼房列表
  delbuilding: baseUrl + "delbuilding",  //楼房删除
  dobuilding: baseUrl + "dobuilding",  //添加楼房
  buildingdetails: baseUrl + "buildingdetails", //楼房详情
  modifybuilding: baseUrl + "modifybuilding",  //修改楼房信息
  nursingprojectlist: baseUrl + "nursingprojectlist",  //护理项目类别列表
  buildingcodelist: baseUrl + "buildingcodelist",  //楼房列表导航
  selectBuildingList: baseUrl + "area/building/kvlist",  //楼房选择kv列表
  floorcodelist: baseUrl + "floorcodelist",  //楼层列表导航
  selectFloorList: baseUrl + "area/floor/kvlist",  //楼层选择kv列表
  roomcodelist: baseUrl + "roomcodelist",  //房间列表导航
  selectRoomList: baseUrl + "area/room/kvlist",  //房间选择kv列表
  bedcodelist: baseUrl + "bedcodelist",  //床位列表导航
  selectBedList: baseUrl + "area/bed/kvlist",  //床位选择kv列表
  bednolist: baseUrl + "bednolist",  //床位类型列表（不分页）
  floorlist: baseUrl + "floorlist",  //楼层列表
  dofloor: baseUrl + "dofloor",  //楼层增加接口
  floordetails: baseUrl + "floordetails",  //楼层详情
  modifyfloor: baseUrl + "modifyfloor",  //修改楼层信息
  delfloor: baseUrl + "delfloor",  //删除楼层
  roomlist: baseUrl + "roomlist",  //房间列表接口
  doroom: baseUrl + "doroom",  //增加房间接口
  roomdetails: baseUrl + "roomdetails",  //查看房间详情
  modifyroom: baseUrl + "modifyroom",  //修改房间
  delroom: baseUrl + "delroom",  //删除房间
  bedlist: baseUrl + "bedlist",  //床位列表
  beddetails: baseUrl + "beddetails",  //床位详情查看
  dobed: baseUrl + "dobed",  //床位增加接口
  modifybed: baseUrl + "modifybed",  //床位修改接口
  delbed: baseUrl + "delbed",  //床位删除接口
  accidenttype: baseUrl + "accidenttype",  //添加事故类型
  accidenttypelist: baseUrl + "accidenttypelist",  //事故类型列表
  accidenttypeinfo: baseUrl + "accidenttypeinfo",  //事故类型详情
  accidenttypedel: baseUrl + "accidenttypedel",  //删除事故类型
  elderregistrationlist: baseUrl + "elderregistrationlist", //评估登记列表
  addelderregistration: baseUrl + "addelderregistration", //添加、更新评估登记表
  delelderregistration: baseUrl + "delelderregistration", //删除评估登记表
  detailelderregistration: baseUrl + "detailelderregistration", //评估登记表详情表
  manageindex: baseUrl + "manageindex", //老人入住管理、床位首页
  abilitylist: baseUrl + "abilitylist",  //能力评估
  delability: baseUrl + "delability",  //删除老人的能力评估列表
  elderhealthevaluations: baseUrl + "elderhealthevaluations",  //能力评估详情
  addelderinfo: baseUrl + "addelderinfo",   //基本信息登记
  addelderHealth: baseUrl + "addelderHealth", //长者能力评估
  getelderhealthexaminationslist: baseUrl + "getelderhealthexaminationslist", //体检登记列表
  addelderhealthexaminations: baseUrl + "addelderhealthexaminations", //添加修改老人体检
  elderhealthexaminationsdetail: baseUrl + "elderhealthexaminationsdetail", //体检登记详情查看
  elderhealthexaminationsearch: baseUrl + "elderhealthexaminationsearch", //体检登记搜索接口
  delelderhealthexaminations: baseUrl + "delelderhealthexaminations", //体检登记删除
  elderhealthhospitalizinglist: baseUrl + "elderhealthhospitalizinglist", //老人就医列表
  addelderhealthhospitalizings: baseUrl + "addelderhealthhospitalizings", //增加修改老人就医
  elderhealthhospitalizingdetail: baseUrl + "elderhealthhospitalizingdetail", //就医详情查看
  elderhealthhospitalizingsearch: baseUrl + "elderhealthhospitalizingsearch",  //就医登记搜索接口
  elderhealthhospitalizingdel: baseUrl + "elderhealthhospitalizingdel", //就医登记删除
  foodtypelist: baseUrl + "foodtypelist", //食品类别列表接口
  foodtype: baseUrl + "foodtype", //增加/编辑食品类别
  foodtypedel: baseUrl + "foodtypedel", //食品类表删除接口
  foodtypedetails: baseUrl + "foodtypedetails",  //食物类别详情
  food: baseUrl + "food",  //添加食物
  foodlist: baseUrl + "foodlist",  //食物列表
  foodinfo: baseUrl + "foodinfo",  //食物详情
  fooddel: baseUrl + "fooddel",  //删除食物
  deliveryAreasList: baseUrl + "deliveryAreasList",  //送餐区域列表
  deletedeliveryareas: baseUrl + "deletedeliveryareas",  //删除送餐区域
  adddelivery: baseUrl + "adddelivery",  //添加编辑送餐区域
  deliveryDetail: baseUrl + "deliveryDetail",  //送餐区域详情
  deliveryareaslists: baseUrl + "deliveryareaslists",  //送餐区域对应区域列表
  adddeliveryareas: baseUrl + "adddeliveryareas",  //添加送餐区域对应区域列表的接口/更新记录的
  deletemealdeliveryareas: baseUrl + "deletemealdeliveryareas",  //删除送餐区域对应区域列表
  deliverylistsdetail: baseUrl + "deliverylistsdetail",  //获取送餐区域对应区域列表详情
  foodorderlist: baseUrl + "foodorderlist", //点餐信息列表
  addfoodorder: baseUrl + "addfoodorder", //点餐信息录入
  fooddelivery: baseUrl + "fooddelivery", //点击送餐
  foodorderslist: baseUrl + "foodorderslist",  //送餐记录列表
  recipeslist: baseUrl + "recipeslist",  //食谱类型列表
  addrecipestypes: baseUrl + "addrecipestypes",  //添加/编辑食谱类型
  deletetypes: baseUrl + "deletetypes",  //删除食谱类型
  recipesdetail: baseUrl + "recipesdetail",  //食谱类型详情
  recipescheduledschemesList: baseUrl + "recipescheduledschemesList",  //食谱列表接口
  delrecipescheduledschemes: baseUrl + "delrecipescheduledschemes",  //删除食谱接口
  employeeslist: baseUrl + "employeeslist", //查看护工列表
  releaserecipescheduledschemes: baseUrl + "releaserecipescheduledschemes",  //发布食谱接口
  recipesearch: baseUrl + "recipesearch", //食谱搜索接口
  addrecipescheduledschemes: baseUrl + "addrecipescheduledschemes", //食谱增加接口
  recipeweek: baseUrl + "recipeweek",  //食谱的时间返回
  druglist: baseUrl + "druglist",  //药品字典列表
  druginfo: baseUrl + "druginfo",  //药品字典详情
  adddrug: baseUrl + "adddrug",  //添加药品字典
  deldrug: baseUrl + "deldrug",  //删除药品字典
  getmonthelderbrithday: baseUrl + "getmonthelderbrithday",  //获取当月老人生日
  getdayelderbrithday: baseUrl + "getdayelderbrithday",  //获取当天过生日的老人
  careactivitieslist: baseUrl + "careactivitieslist",  //老人活动列表
  careactivitiesdetail: baseUrl + "careactivitiesdetail", //老人活动详情
  addcareactivities: baseUrl + "addcareactivities",  //添加/修改老人活动
  careactivitiesdel: baseUrl + "careactivitiesdel",  //删除老人活动记录
  careactivitiessearch: baseUrl + "careactivitiessearch",  //搜索老人活动
  uploadcareactivities: baseUrl + "uploadcareactivities",  //上传活动图片
  drugsafekeeplist: baseUrl + "drugsafekeeplist",  //药物缴存列表
  adddrugsafekeep: baseUrl + "adddrugsafekeep",  //添加药物缴存
  recipedetail: baseUrl + "recipedetail",  //食谱详情
  modifyrecipe: baseUrl + "modifyrecipe",  //食物安排修改接口
  elderdruglist: baseUrl + "elderdruglist", //老人缴存药品列表
  deldrugsafekeeping: baseUrl + "deldrugsafekeeping",  //退缴药品
  medicationsetlist: baseUrl + "medicationsetlist",  //老人用药设置表
  addmedicationset: baseUrl + "addmedicationset",  //添加用药设置
  delmedicationset: baseUrl + "delmedicationset",  //删除用药设置
  deleldermedicationset: baseUrl + "deleldermedicationset",  //用药设置批量删除
  elderset: baseUrl + "elderset",  //老人用药列表
  recipeexport: baseUrl + "recipeexport", //食谱导出
  getsearchelder: baseUrl + "getsearchelder",  //获取为退住的老人
  getnuringemployeelist: baseUrl + "getnuringemployeelist",  //护理人员列表
  getnursingworkergroups: baseUrl + "getnursingworkergroups",  //获取护工小组
  medicationrecordalllist: baseUrl + "medicationrecordalllist",  //用药登记菜单列表
  eldersdministrationlist: baseUrl + "eldersdministrationlist",  //老人名下已设置用药列表
  addmedicationrecord: baseUrl + "addmedicationrecord",  //用药登记
  medicationrecordlist: baseUrl + "medicationrecordlist",  //个人用药登记列表
  dictionaryList: baseUrl + "system/data/dictionary/getlist",  //获取字典项管理列表
  groupList: baseUrl + "system/data/group/getkvlist", //获取字典分组键值对数据
  gettreelist: baseUrl + "system/data/group/gettreelist",  //获取字典分组树形菜单数据
  save: baseUrl + "system/data/dictionary/save",  //添加字典项
  delete: baseUrl + "system/data/dictionary/delete",  //删除字典项
  update: baseUrl + "system/data/dictionary/update", //保存编辑字典项
  bednolist: baseUrl + "bednolist",  //床位类型小接口
  addfeelists: baseUrl + "addfeelists",  //普通消费登记
  addfixfeelists: baseUrl + "addfixfeelists",  //水电费消费登记
  getcosttypelist: baseUrl + "getcosttypelist", //费用类别分页列表
  getretreatsettlement: baseUrl + "getretreatsettlement",  //退住结算的列表
  getretreatsettlementdetail: baseUrl + "getretreatsettlementdetail",  //账单情况
  elderfeelist: baseUrl + "elderfeelist",  //缴费列表
  getImpredetaillist: baseUrl + "getImpredetaillist",  //交费登记列表
  feetypelist: baseUrl + "feetypelist",  //费用类型列表
  feemanagedetail: baseUrl + "feemanagedetail",  //欠费管理详情
  feementdetail: baseUrl + "feementdetail",  //入住缴费详情
  getpricelist: baseUrl + "getpricelist",  //缴费登记/修改缴费登记所需缴费列表
  feemanagestore: baseUrl + "feemanagestore",  //欠费登记交费
  nwgroup: baseUrl + "nwgroup", //添加护工小组
  nwgrouplist: baseUrl + "nwgrouplist",  //护工小组列表
  nwgroupinfo: baseUrl + "nwgroupinfo",  //护工小组详情
  nwgroupdel: baseUrl + "nwgroupdel",  //删除护工小组
  nlevellist: baseUrl + "nlevellist",  //护理级别列表
  nleveldel: baseUrl + "nleveldel",  //删除护理级别
  nlevel: baseUrl + "nlevel",  //添加护理级别/修改护理级别
  nlevelinfo: baseUrl + "nlevelinfo",  //护理级别详情
  nursingprojectlist: baseUrl + "nursingprojectlist",  //护理项目类别列表
  nursingproject: baseUrl + "nursingproject", //增加/编辑项目类别
  nursingprojectdel: baseUrl + "nursingprojectdel",  //护理类别删除
  nursingitemslist: baseUrl + "nursingitemslist",  //护理项目列表
  addnursingitems: baseUrl + "addnursingitems",  //添加护理项目
  nursingitemsdetail: baseUrl + "nursingitemsdetail",  //护理项目详情
  deleteitems: baseUrl + "deleteitems",  //删除护理项目
  nursingprojectdetails: baseUrl + "nursingprojectdetails",  //护理类别详情
  billdetail: baseUrl + "billdetail",  //欠费管理账单
  schedulinglist: baseUrl + "schedulinglist",  //排班方案表列表
  addscheduling: baseUrl + "addscheduling",  //添加排班方案
  schedulingdetail: baseUrl + "schedulingdetail",  //排班数据的详情
  deletescheduling: baseUrl + "deletescheduling",  //护工排班方案删除
  workshift: baseUrl + "workshift",  //添加护工替班
  workshiftlist: baseUrl + "workshiftlist",  //护工替班列表
  workshiftinfo: baseUrl + "workshiftinfo",  //护工替班详情
  workshiftdel: baseUrl + "workshiftdel",  //删除护工替班
  deletetimeplans: baseUrl + "deletetimeplans",  //删除护工排班方案班次
  imprestdeposit: baseUrl + "imprestdeposit",  //老人预存总额和押金总额
  workschemeslist: baseUrl + "workschemeslist",  //护工排班列表接口
  delworkschemes: baseUrl + "delworkschemes",  //删除排班安排
  checkoutfeelist: baseUrl + "checkoutfeelist",  //退住结算月账单详情
  feedetaillist: baseUrl + "feedetaillist",  //月账单下详细收费列表
  improvefeedetail: baseUrl + "improvefeedetail",  //调整月账单
  approveworkshift: baseUrl + "approveworkshift",  //护工替班审批
  successordetail: baseUrl + "successordetail",  //替班筛选
  addretreatsettlement: baseUrl + "addretreatsettlement",  //新增退住结算（其他退费）
  doschedulinglist: baseUrl + "doschedulinglist",  //获取所有的排班方案
  doschedulingtime: baseUrl + "doschedulingtime",  //获取排班的时间
  getcycle: baseUrl + "getcycle",  //获取月 周列表
  workschemes: baseUrl + "workschemes",  //增加/修改护工排班接口
  getworkschemes: baseUrl + "getworkschemes",  //员工排班详情查看
  getbuild: baseUrl + "getbuild",  //楼房列表(护工小组)
  getfloor: baseUrl + "getfloor",  //楼层列表(护工小组)
  getroom: baseUrl + "getroom",  //房间列表(护工小组)
  employeessearch: baseUrl + "employeessearch",  //护工搜索接口
  employeesdel: baseUrl + "employeesdel",  //护工删除
  employeesdetails: baseUrl + "employeesdetails",  //护工查看接口
  addemployees: baseUrl + "addemployees",  //增加修改护工接口
  getworkergroupsolder: baseUrl + "getworkergroupsolder",  //通过护工小组获取老人
  addnursingworker: baseUrl + "addnursingworker",  //给老人添加护工
  getemployeetypelist: baseUrl + "getemployeetypelist",  //获取人员岗位类表
  getdepartmentslist: baseUrl + "getdepartmentslist",  //获取部门列表
  employeecertificatesdel: baseUrl + "employeecertificatesdel",  //员工证书删除
  nursarealist: baseUrl + "nursarealist",  //护工小组绑定房间列表
  nursareadel: baseUrl + "nursareadel",  //单个删除护工小组绑定的房间
  systemList: baseUrl + "system/log/action/list",  //操作日志列表
  elderrelativeinfo: baseUrl + "elderrelativeinfo",  //家属详情
  addelderrelative: baseUrl + "addelderrelative",  //新增家属登记/修改家属登记
  delelderrelative: baseUrl + "delelderrelative",  //删除家属
  elderhealthinfo: baseUrl + "elderhealthinfo",  //老人健康信息详情
  addelderhealth: baseUrl + "addelderhealth",  //老人健康信息登记/修改老人健康信息
  elderrecipebed: baseUrl + "elderrecipebed",  //餐饮床位绑定
  getshowdepartmentslist: baseUrl + "getshowdepartmentslist",  //获取部门列表
  adddepartments: baseUrl + "adddepartments",  //添加部门
  departmentsdetail: baseUrl + "departmentsdetail",  //部门查看
  departmentsdel: baseUrl + "departmentsdel",  //部门删除
  getdepartmentsemployeelist: baseUrl + "getdepartmentsemployeelist",  //获取部门下的员工
  elderrecipebedinfo: baseUrl + "elderrecipebedinfo",  //餐饮床位详情
  addeldernurscheme: baseUrl + "addeldernurscheme",  //老人入住绑定护理套餐
  eldernurschemelist: baseUrl + "eldernurschemelist",  //老人入住选择的护理项目列表
  eldernurschemeinfo: baseUrl + "eldernurschemeinfo",  //老人入住选择的护理详情
  addfeesettlement: baseUrl + "addfeesettlement",  //入院缴费登记/缴费登记
  penulist: baseUrl + "penulist",  //权限菜单列表
  getallemployeelist: baseUrl + "getallemployeelist",   //所有员工
  detailability: baseUrl + "detailability",  //老人能力评估详情
  appointmentmovein: baseUrl + "appointmentmovein",  //预约转入住
  careactivitieselder: baseUrl + "careactivitieselder",  //老人活动获取参加老人id
  uploademployeeimage: baseUrl + "uploademployeeimage",  // 上传护工照片
  uploadelderimage: baseUrl + "uploadelderimage",  //上传老人照片
  uploadelderhealthexaminationimage: baseUrl + "uploadelderhealthexaminationimage",  //上传体检照片
  uploadaccidentimage: baseUrl + "uploadaccidentimage",  //事故记录的图片
  elderlist: baseUrl + "elderlist",//老人档案列表
  elderdetail: baseUrl + "elderdetail",//老人资料详情
  healthstatistics: baseUrl + "statistic/elder/disease",  //老人疾病统计
  modifiyelder: baseUrl + "modifiyelder",  //老人基本信息保存
  bedstatistics: baseUrl + "bedstatistics",  //床位使用率统计
  eldercheckoutstatistics: baseUrl + "eldercheckoutstatistics",  //老人出入统计
  eldercheckinstatistics: baseUrl + "eldercheckinstatistics",  //老人出入报表统计
  getbedoccupyrate: baseUrl + "getbedoccupyrate",  //床位入住率统计
  searchelders: baseUrl + "searchelders",  //老人列表下拉框
  geteldernursingscheme: baseUrl + "geteldernursingscheme",  //老人护理信息
  versionlogs: baseUrl + "versionlogs",  //版本日志获取
  getelderdruglist: baseUrl + "getelderdruglist",  //老人缴存药品信息
  getrepositorylist: baseUrl + "getrepositorylist",  //查看仓库列表
  delrepository: baseUrl + "delrepository",  //删除仓库
  getrepokv: baseUrl + "getrepokv",   //仓库设置预置数据
  addrepository: baseUrl + "addrepository",  //新增仓库
  viewrepository: baseUrl + "viewrepository",  //查看仓库信息
  getgoodscategorylist: baseUrl + "getgoodscategorylist",  //查看物资分类列表
  delgoodscategory: baseUrl + "delgoodscategory",  //删除物资类别
  addgoodscategory: baseUrl + "addgoodscategory",  //新增/修改物资类别
  getgoodslist: baseUrl + "getgoodslist",  //查看物资列表
  addgoods: baseUrl + "addgoods",  //新增/修改物资
  delgoods: baseUrl + "delgoods",  //删除物资
  viewgoodscategory: baseUrl + "viewgoodscategory",  //物资分类详情
  viewgoods: baseUrl + "viewgoods",  //物资详情
  getinventoryincomelist: baseUrl + "getinventoryincomelist",  //入库记录列表
  addinventoryincome: baseUrl + "addinventoryincome",  ///入库登记
  delinventoryincome: baseUrl + "delinventoryincome",  //删除入库记录
  viewinventoryincome: baseUrl + "viewinventoryincome",  //查看入库记录信息
  getincomelistkv: baseUrl + "getincomelistkv",  //查看入库记录列表预置数据
  getincomekv: baseUrl + "getincomekv",  //新增入库记录预置数据
  modifyinventoryincome: baseUrl + "modifyinventoryincome",  //修改入库物资价格
  getinventoryoutcomelist: baseUrl + "getinventoryoutcomelist",  //出库记录列表
  getoutcomekv: baseUrl + "getoutcomekv",  //出库登记预置数据
  viewinventoryoutcome: baseUrl + "viewinventoryoutcome",  //查看出库记录信息
  addinventoryoutcome: baseUrl + "addinventoryoutcome",  //出库登记
  allrepository: baseUrl + "allrepository",  //所有仓库列表
  getinventorygoodslist: baseUrl + "getinventorygoodslist",  //查看库存列表
  getmonthlylist: baseUrl + "getmonthlylist",  //月度盘查列表
  getrepositorymoneylist: baseUrl + "getrepositorymoneylist",  //库存金额列表
  getallotkv: baseUrl + "getallotkv",  //调拨申请列表预置数据
  getallotapplylist: baseUrl + "getallotapplylist",  //物资调拨申请列表
  viewallotapply: baseUrl + "viewallotapply",  //查看调拨申请详情
  allotapply: baseUrl + "allotapply",  //调拨申请
  allotapprove: baseUrl + "allotapprove",  //调拨审批
  getcheckrepo: baseUrl + "getcheckrepo",  //库存盘点仓库列表
  addinventorycheck: baseUrl + "addinventorycheck",  //新增库存盘点
  getcheckgoodslist: baseUrl + "getcheckgoodslist",  //库存盘点物资列表
  viewinventorycheck: baseUrl + "viewinventorycheck",  //查看库存盘点记录
  getcheckgoodsorderlist: baseUrl + "getcheckgoodsorderlist",  //库存盘点物资订单列表
  getinventorychecklist: baseUrl + "getinventorychecklist",  //库存盘点列表
  getrepositoryallgoods: baseUrl + "getrepositoryallgoods",  //获取仓库里的物资列表
  viewgoodscheck: baseUrl + "viewgoodscheck",  //查看库存盘点操作记录
  getrepositorygoodsorderlist: baseUrl + "getrepositorygoodsorderlist",  //仓库物资订单列表
  operationYearList: baseUrl + "statistic/org/operation/year",  //年统计列表
  operationYearExport: baseUrl + "statistic/org/operation/year/export",  //年统计列表导出
  employeeinfolist: baseUrl + "employeeinfolist",  //所有员工列表
  operattionYearChart: baseUrl + "statistic/org/operation/year/chart",  //年运营统计图表数据
  employeeinfoexport: baseUrl + "employeeinfoexport",  //员工数据导出
  employeeinfoimport: baseUrl + "employeeinfoimport",  //员工导入
  operationMonthList: baseUrl + "statistic/org/operation/month",  //月运营统计列表
  operationMonthExport: baseUrl + "statistic/org/operation/month/export",  //月运营统计列表导出
  operattionMonthChart: baseUrl + "statistic/org/operation/month/chart",  //月运营统计图表数据
  elderinfoexport: baseUrl + "elderinfoexport",  //老人信息导出
  eldernursingtype: baseUrl + "eldernursingtype",  //护理类型统计
  eldernursingtypexport: baseUrl + "eldernursingtypexport",  //护理类型统计导出
  eldercheckoutexport: baseUrl + "eldercheckoutexport",  //老人出入统计数据导出
  getelderagestatistics: baseUrl + "getelderagestatistics",  //老人年龄统计数据获取
  exportelderagestatistics: baseUrl + "exportelderagestatistics",  //老人年龄统计数据导出
  exportbedoccupyrate: baseUrl + "exportbedoccupyrate",  //床位入住率统计导出
  eldercheckinexport: baseUrl + "eldercheckinexport",  //老人出入报表数据导出
  beduseage: baseUrl + "statistic/org/bed/usage", //床位使用统计
  badstatusexport: baseUrl + "statistic/org/bed/usage/export", //床位使用统计导出
  bedstatus: baseUrl + "statistic/org/bed/status", //床位状态统计
  bedstatuschart: baseUrl + "statistic/org/bed/status/chart", //床位状态统计图表
  bedstatusexport: baseUrl + "statistic/org/bed/status/export", //床位状态统计导出
  eldertype: baseUrl + "statistic/elder/type", //老人类型统计
  eldertypechart: baseUrl + "statistic/elder/type/chart", //老人类型统计图表
  eldertypeexport: baseUrl + "statistic/elder/type/export", //老人类型统计导出
  employeelist: baseUrl + "employeelist",  //员工信息详情
  exportemployeelist: baseUrl + "exportemployeelist",  //员工详情列表导出
  employeejobstatistic: baseUrl + "employeejobstatistic",  //员工岗位分析
  exportemployeejobstatistic: baseUrl + "exportemployeejobstatistic",  //员工岗位分析数据导出
  geteldernursinglevelstatistics: baseUrl + "geteldernursinglevelstatistics",  //老人护理级别统计获取
  exporteldernursinglevelstatistics: baseUrl + "exporteldernursinglevelstatistics",  //老人护理级别统计数据导出
  employeeagestatistic: baseUrl + "employeeagestatistic", //员工年龄分析
  exportemployeeagestatistic: baseUrl + "exportemployeeagestatistic", //员工年龄分析数据导出
  employeeeducationstatistic: baseUrl + "employeeeducationstatistic", //员工学历分析
  exportemployeeeducationstatistic: baseUrl + "exportemployeeeducationstatistic", //员工学历分析数据导出
  getemployeeprolevelstatistic: baseUrl + "getemployeeprolevelstatistic", //护理员资质分析
  exportemployeeprolevelstatistic: baseUrl + "exportemployeeprolevelstatistic", //护理员资质分析导出
  exportelderdisease: baseUrl + "statistic/elder/disease/export",  //老人疾病统计导出
  getnurses: baseUrl + "getnurses",  //护工列表详细信息
  getbed: baseUrl + "getbed",  //床位列表(护工小组)
  addnursesgrouparea: baseUrl + "addnursesgrouparea",  //护工小组绑定护理区域
  eldermanagementexport: baseUrl + "eldermanagementexport", //老人管理信息导出
  getnursegroupareascope: baseUrl + "getnursegroupareascope",  //获取楼栋楼层房间床位
  eldermanagementlist: baseUrl + "eldermanagementlist",  //老人管理入住老人管理
  eldermanagementexport: baseUrl + "eldermanagementexport",  //老人管理信息导出
  getnursegrouplist: baseUrl + "getnursegrouplist",  //获取护工小组列表(全部)
  getgroupnurses: baseUrl + "getgroupnurses",  //获取小组护工列表
  getnurseareascope: baseUrl + "getnurseareascope",  //护工获取护理区域
  addnursesarea: baseUrl + "addnursesarea",  //护工绑定护理区域
  indexinfo: baseUrl + "indexinfo",  //统计首页需要的具体信息
  chekinnursinglevelstatis: baseUrl + "chekinnursinglevelstatis",  //首页所需护理等级统计
  examinationstatis: baseUrl + "examinationstatis",  //获取当周进行体检登记的老人
  weekbedtypestatis: baseUrl + "weekbedtypestatis",  //当周预约入住的床位统计
  accidenttypestatis: baseUrl + "accidenttypestatis",  //事故类型当月统计
  accidentstatis: baseUrl + "accidentstatis",  //突发事件老人统计
  inventoryshortagestock: baseUrl + "inventoryshortagestock",  //紧缺物资库存
  weeklyscheme: baseUrl + "weeklyscheme",  //本周护工排班
  getnurseext: baseUrl + "getnurseext", //查看护工资料
  setnurseext: baseUrl + "setnurseext", //设置护工资料
  gettasklist: baseUrl + "gettasklist", //护工每日任务列表
  exporttasklist: baseUrl + "exporttasklist", //护工每日任务列表导出
  exporttasksummarylist: baseUrl + "exporttasksummarylist", //护工每日任务统计导出
  gettasksummarylist: baseUrl + "gettasksummarylist", //护工每日任务统计
  gettasknurses: baseUrl + "gettasknurses", //每日任务护工列表
  gettaskelders: baseUrl + "gettaskelders", //每日任务老人列表
  addnotice: baseUrl + "system/notice/add", //新增养老院公告
  noticelist: baseUrl + "system/notice/list", //查看养老院公告列表
  deletenotice: baseUrl + "system/notice/delete", //删除养老院公告
  getnursescorerecords: baseUrl + "getnursescorerecords", //查看护工积分列表
  getnursescores: baseUrl + "getnursescores", //查看护工总积分
  orderlist: baseUrl + "timebank/order/list", //时间银行订单列表
  getdistrictlist: baseUrl + "getdistrictlist", //地区列表获取
  savehotelinfo: baseUrl + "savehotelinfo", //保存养老院基本信息
  monthBills: baseUrl + "fee/monthbills/list/checkin",  //月账单列表
  uploadhotelimage: baseUrl + "uploadhotelimage", //养老院图片上传保存
  getattrlist: baseUrl + "getattrlist", //获取养老院属性列表
  bankServe: baseUrl + "timebank/serve/statistics",  //服务统计
  bankServeList: baseUrl + "timebank/serve/list",  //服务记录
  serveDetail: baseUrl + "timebank/serve/detail",  //服务详情
  nursingworker: baseUrl + "nursingworker/lists", //养老之家护工列表
  delnursingworker: baseUrl + "nursingworker/deluser", //养老之家护工删除
  gethotelinfo: baseUrl + "gethotelinfo", //养老之家养老院基础信息获取
  storenursingworker: baseUrl + "nursingworker/activeunuseduser", //养老之家护工编辑添加
  getbedtypelist: baseUrl + "getbedtypelist", //养老之家获取床位类型价格列表
  serveExport: baseUrl + "timebank/serve/statistics/export",  //服务统计导出
  updatebedtype: baseUrl + "updatebedtype", //养老之家床位类型信息编辑
  gethotelnaturelist: baseUrl + "gethotelnaturelist",  //养老院社会类型获取
  getunuseduserlist: baseUrl + "nursingworker/getunuseduserlist",  //获取已经删除的护工信息
  nursingworkerstore: baseUrl + "nursingworker/updateuser",  //护工编辑
  uploadnursingitem: baseUrl + "uploadnursingitem",  //上传护理项目照片
  systemSave: baseUrl + "system/config/save",  //设置选项添加修改接口
  systemDetail: baseUrl + "system/config/detail",  //设置详情
}
